import { useEffect, useMemo, useState } from 'react';
import { BarChart3, Building2, ChevronDown, CreditCard, FilePlus2, FileText, LayoutDashboard, LogIn, MoreHorizontal, Plus, ReceiptText, Settings2, ShieldCheck, Trash2, UserCircle2, Users, WalletCards, X } from 'lucide-react';
import { onAuthStateChanged, sendPasswordResetEmail, signOut, updateProfile, type User } from 'firebase/auth';
import { doc, getDoc, setDoc } from 'firebase/firestore';
import { auth, db } from './lib/firebase';
import OwnerTopUp from './OwnerTopUp';
import DocumentWorkflow from './DocumentWorkflow';
import BillingCenter from './BillingCenter';

type Doc = { id:string; number:string; customer:string; total:number; status:'Draft'|'Sent'|'Paid'|'Overdue'; due:string; kind?:'Invoice'|'Quotation' };
type Customer = { id:string; name:string; email:string; phone:string; outstanding:number };
type Expense = { id:string; category:string; note:string; amount:number; date:string };
type Receipt = { id:string; number:string; invoiceNumber:string; customer:string; amount:number; date:string; reference:string };
const seedDocs:Doc[]=[{id:'1',number:'INV-0001',customer:'Apex Stores',total:125000,status:'Paid',due:'2026-09-03',kind:'Invoice'},{id:'2',number:'INV-0002',customer:'Mira Events',total:78000,status:'Sent',due:'2026-09-18',kind:'Invoice'},{id:'3',number:'INV-0003',customer:'Northline Media',total:210000,status:'Overdue',due:'2026-08-30',kind:'Invoice'},{id:'4',number:'QUO-0001',customer:'Lagos Creative',total:95000,status:'Draft',due:'2026-09-20',kind:'Quotation'}];
const seedCustomers:Customer[]=[{id:'1',name:'Apex Stores',email:'accounts@apex.example',phone:'0800 000 0001',outstanding:0},{id:'2',name:'Mira Events',email:'hello@mira.example',phone:'0800 000 0002',outstanding:78000},{id:'3',name:'Northline Media',email:'finance@northline.example',phone:'0800 000 0003',outstanding:210000}];
const seedExpenses:Expense[]=[{id:'1',category:'Transport',note:'Client delivery',amount:12000,date:'2026-09-07'},{id:'2',category:'Internet',note:'Business data',amount:18000,date:'2026-09-05'}];
const money=(n:number)=>`₦${n.toLocaleString('en-NG')}`;
const persist=<T,>(key:string,value:T)=>localStorage.setItem(`donidex:${key}`,JSON.stringify(value));
const load=<T,>(key:string,fallback:T):T=>{try{const raw=localStorage.getItem(`donidex:${key}`);return raw?JSON.parse(raw) as T:fallback}catch{return fallback}};

export default function App(){
 const [menuOpen,setMenuOpen]=useState(false); const [view,setView]=useState('Dashboard');
 const [docs,setDocs]=useState<Doc[]>(()=>load('docs',seedDocs)); const [customers,setCustomers]=useState<Customer[]>(()=>load('customers',seedCustomers)); const [expenses,setExpenses]=useState<Expense[]>(()=>load('expenses',seedExpenses)); const [receipts,setReceipts]=useState<Receipt[]>(()=>load('receipts',[]));
 const [modal,setModal]=useState<'profile'|'settings'|'security'|'plans'|'ownerTopUp'|null>(null); const [selectedDoc,setSelectedDoc]=useState<Doc|null>(null); const [notice,setNotice]=useState('');
 const [profile,setProfile]=useState(()=>load('profile',{username:'DONIDEX User',email:''})); const [business,setBusiness]=useState(()=>load('business',{name:'My Business',phone:'',email:'',address:'',tax:0,prefix:'INV',next:5}));
 const [user,setUser]=useState<User|null>(auth?.currentUser || null); const [profileBusy,setProfileBusy]=useState(false); const [securityBusy,setSecurityBusy]=useState(false);
 useEffect(()=>persist('docs',docs),[docs]); useEffect(()=>persist('customers',customers),[customers]); useEffect(()=>persist('expenses',expenses),[expenses]); useEffect(()=>persist('receipts',receipts),[receipts]); useEffect(()=>persist('profile',profile),[profile]); useEffect(()=>persist('business',business),[business]);
 useEffect(()=>{if(!auth)return;return onAuthStateChanged(auth,async value=>{setUser(value);if(value&&db){const snap=await getDoc(doc(db,'userProfiles',value.uid));if(snap.exists()){const data=snap.data() as any;setProfile(p=>({...p,username:data.displayName||value.displayName||p.username,email:value.email||p.email}));}else setProfile(p=>({...p,username:value.displayName||p.username,email:value.email||p.email}));}})},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(t)},[notice]);
 const revenue=useMemo(()=>docs.filter(d=>d.status==='Paid').reduce((s,d)=>s+d.total,0),[docs]); const outstanding=useMemo(()=>docs.filter(d=>d.status!=='Paid').reduce((s,d)=>s+d.total,0),[docs]); const overdue=useMemo(()=>docs.filter(d=>d.status==='Overdue').reduce((s,d)=>s+d.total,0),[docs]); const spend=useMemo(()=>expenses.reduce((s,e)=>s+e.amount,0),[expenses]);
 const nav=(next:string)=>{setView(next);setMenuOpen(false);setModal(null)};
 const addInvoice=()=>{const n=`${business.prefix}-${String(business.next).padStart(4,'0')}`;setDocs(d=>[{id:crypto.randomUUID(),number:n,customer:'New Customer',total:0,status:'Draft',due:new Date().toISOString().slice(0,10),kind:'Invoice'},...d]);setBusiness(b=>({...b,next:b.next+1}));setNotice(`${n} created as draft.`)};
 const addQuotation=()=>{const n=`QUO-${String(docs.filter(d=>d.kind==='Quotation').length+1).padStart(4,'0')}`;setDocs(d=>[{id:crypto.randomUUID(),number:n,customer:'New Customer',total:0,status:'Draft',due:new Date().toISOString().slice(0,10),kind:'Quotation'},...d]);setNotice(`${n} created as quotation.`)};
 const addCustomer=()=>{setCustomers(c=>[{id:crypto.randomUUID(),name:'New Customer',email:'',phone:'',outstanding:0},...c]);setNotice('Customer added.')};
 const addExpense=()=>{setExpenses(e=>[{id:crypto.randomUUID(),category:'General',note:'New expense',amount:0,date:new Date().toISOString().slice(0,10)},...e]);setNotice('Expense added.')};
 const saveProfile=async()=>{setProfileBusy(true);try{if(auth?.currentUser){if(profile.username.trim()&&auth.currentUser.displayName!==profile.username.trim())await updateProfile(auth.currentUser,{displayName:profile.username.trim()});if(db)await setDoc(doc(db,'userProfiles',auth.currentUser.uid),{uid:auth.currentUser.uid,email:auth.currentUser.email||profile.email,displayName:profile.username.trim(),updatedAt:new Date().toISOString()},{merge:true});}persist('profile',profile);setNotice('Profile saved securely.');setModal(null)}catch(e){setNotice(e instanceof Error?e.message:'Could not save profile.')}finally{setProfileBusy(false)}};
 const resetPassword=async()=>{if(!user?.email){setNotice('No verified email is available for this account.');return}setSecurityBusy(true);try{await sendPasswordResetEmail(auth!,user.email);setNotice('Password reset link sent to your email.')}catch(e){setNotice(e instanceof Error?e.message:'Could not send password reset link.')}finally{setSecurityBusy(false)}};
 const logout=async()=>{if(!auth)return;setSecurityBusy(true);try{await signOut(auth);setNotice('Signed out.')}catch(e){setNotice(e instanceof Error?e.message:'Could not sign out.')}finally{setSecurityBusy(false)}};
 return <div className="app-shell">
  <header className="topbar"><button className="brand" onClick={()=>setMenuOpen(v=>!v)} aria-expanded={menuOpen}><span className="brand-mark">D</span><span>DONIDEX</span><ChevronDown size={16}/></button>{menuOpen&&<div className="brand-menu"><button onClick={()=>{setModal('profile');setMenuOpen(false)}}><UserCircle2 size={15}/> User Profile</button><button onClick={()=>{setModal('settings');setMenuOpen(false)}}><Building2 size={15}/> Business Settings</button><button onClick={()=>{setModal('security');setMenuOpen(false)}}><ShieldCheck size={15}/> Security & Account</button><button onClick={()=>{setModal('plans');setMenuOpen(false)}}><CreditCard size={15}/> Plans & Billing</button>{auth?.currentUser?.email?.toLowerCase()==='donistudioproduction@gmail.com'&&<button onClick={()=>{setModal('ownerTopUp');setMenuOpen(false)}}><ShieldCheck size={15}/> Owner Top-Up</button>}</div>}<div className="topbar-business"><Building2 size={14}/>{business.name}</div><button className="login" onClick={()=>user?setModal('security'):setNotice('Please use the secure DONIDEX sign-in screen.')}><LogIn size={16}/> {user?'Account':'Sign in'}</button></header>
  <div className="workspace"><aside className="sidebar"><button className={view==='Dashboard'?'nav active':'nav'} onClick={()=>nav('Dashboard')}><LayoutDashboard/>Dashboard</button><button className={view==='Invoices'?'nav active':'nav'} onClick={()=>nav('Invoices')}><FileText/>Invoices</button><button className={view==='Customers'?'nav active':'nav'} onClick={()=>nav('Customers')}><Users/>Customers</button><button className={view==='Expenses'?'nav active':'nav'} onClick={()=>nav('Expenses')}><WalletCards/>Expenses</button><button className={view==='Reports'?'nav active':'nav'} onClick={()=>nav('Reports')}><BarChart3/>Reports</button><button className={view==='Business Hub'?'nav active':'nav'} onClick={()=>nav('Business Hub')}><Settings2/>Business Hub</button></aside>
   <main className="content"><section className="workspace-head"><div><p className="eyebrow">DONIDEX BUSINESS OPERATIONS</p><h1>{view}</h1><p className="muted">{view==='Dashboard'?'Your business pulse at a glance.':`Manage ${view.toLowerCase()} without leaving your workspace.`}</p></div><div className="actions"><button className="secondary" onClick={()=>setModal('plans')}><CreditCard size={15}/> Plans</button>{view==='Invoices'&&<button className="primary" onClick={addInvoice}><Plus size={15}/> New invoice</button>}{view==='Customers'&&<button className="primary" onClick={addCustomer}><Plus size={15}/> New customer</button>}{view==='Expenses'&&<button className="primary" onClick={addExpense}><Plus size={15}/> Add expense</button>}</div></section>
    {view==='Dashboard'&&<><section className="stats-grid"><article className="stat"><span>Revenue</span><strong>{money(revenue)}</strong><small>Paid invoices</small></article><article className="stat"><span>Outstanding</span><strong>{money(outstanding)}</strong><small>Awaiting payment</small></article><article className="stat"><span>Overdue</span><strong>{money(overdue)}</strong><small>Needs follow-up</small></article><article className="stat"><span>Expenses</span><strong>{money(spend)}</strong><small>Recorded spending</small></article></section><section className="dashboard-grid"><article className="panel"><div className="panel-head"><div><p className="eyebrow">RECENT DOCUMENTS</p><h2>Invoice activity</h2></div><button className="ghost" onClick={()=>nav('Invoices')}>View all</button></div><div className="list">{docs.slice(0,4).map(d=><div className="list-row" key={d.id}><div><strong>{d.number}</strong><span>{d.customer}</span></div><div className="row-right"><b>{money(d.total)}</b><em className={`status status-${d.status.toLowerCase().replace(' ','-')}`}>{d.status}</em></div></div>)}</div></article><article className="panel"><div className="panel-head"><div><p className="eyebrow">BUSINESS HUB</p><h2>Growth tools</h2></div><button className="ghost" onClick={()=>nav('Business Hub')}>Open</button></div><div className="hub-grid"><button onClick={()=>setNotice('Recurring invoice workspace is ready for the next migration batch.')}><ReceiptText/><span>Recurring billing</span></button><button onClick={()=>setNotice('Product catalogue workspace is ready for the next migration batch.')}><MoreHorizontal/><span>Products & services</span></button><button onClick={()=>nav('Reports')}><BarChart3/><span>Advanced insights</span></button><button onClick={()=>setNotice('Payment collection workspace is ready for the next migration batch.')}><CreditCard/><span>Payment collection</span></button></div></article></section></>}
    {view==='Invoices'&&<section className="panel"><div className="panel-head"><div><p className="eyebrow">DOCUMENT WORKFLOW</p><h2>Invoices, quotations & receipts</h2></div><div className="actions"><button className="secondary" onClick={addQuotation}>New quotation</button><button className="primary" onClick={addInvoice}><FilePlus2 size={15}/> New invoice</button></div></div><div className="table-list">{docs.map(d=><div className="table-row" key={d.id}><div><strong>{d.number}</strong><span>{d.kind||'Invoice'} · {d.customer}</span></div><b>{money(d.total)}</b><em className={`status status-${d.status.toLowerCase().replace(' ','-')}`}>{d.status}</em><span>{d.due}</span><div className="actions"><button className="ghost" onClick={()=>setSelectedDoc(d)}>Open</button><button className="icon-btn" onClick={()=>{setDocs(x=>x.filter(y=>y.id!==d.id));setNotice('Document deleted.')}} aria-label={`Delete ${d.number}`}><Trash2 size={15}/></button></div></div>)}</div>{selectedDoc&&<DocumentWorkflow doc={selectedDoc} docs={docs} setDocs={setDocs} receipts={receipts} setReceipts={setReceipts} onClose={()=>setSelectedDoc(null)} money={money}/>}<div className="receipt-mini"><p className="eyebrow">RECENT RECEIPTS</p>{receipts.slice(0,4).map(r=><span key={r.id}>{r.number} · {r.invoiceNumber} · {money(r.amount)}</span>)}</div></section>}
    {view==='Customers'&&<section className="panel"><div className="panel-head"><div><p className="eyebrow">RELATIONSHIPS</p><h2>Customers</h2></div><button className="primary" onClick={addCustomer}><Plus size={15}/> New customer</button></div><div className="table-list">{customers.map(c=><div className="table-row" key={c.id}><div><strong>{c.name}</strong><span>{c.email||'No email'} · {c.phone||'No phone'}</span></div><b>{money(c.outstanding)}</b><em>Outstanding</em><button className="ghost" onClick={()=>setNotice(`Payment history for ${c.name} is ready for backend migration.`)}>History</button></div>)}</div></section>}
    {view==='Expenses'&&<section className="panel"><div className="panel-head"><div><p className="eyebrow">SPENDING</p><h2>Expenses</h2></div><button className="primary" onClick={addExpense}><Plus size={15}/> Add expense</button></div><div className="table-list">{expenses.map(e=><div className="table-row" key={e.id}><div><strong>{e.category}</strong><span>{e.note}</span></div><b>{money(e.amount)}</b><em>{e.date}</em><span>Business expense</span></div>)}</div></section>}
    {view==='Reports'&&<section className="reports-grid"><article className="panel report-hero"><p className="eyebrow">BUSINESS INSIGHTS</p><h2>Collection health</h2><strong>{revenue+outstanding?Math.round((revenue/(revenue+outstanding))*100):0}%</strong><span>of invoiced value has been collected.</span></article><article className="panel"><p className="eyebrow">KEY METRICS</p><div className="metric"><span>Revenue</span><b>{money(revenue)}</b></div><div className="metric"><span>Outstanding</span><b>{money(outstanding)}</b></div><div className="metric"><span>Expenses</span><b>{money(spend)}</b></div><div className="metric"><span>Net pulse</span><b>{money(revenue-spend)}</b></div></article></section>}
    {view==='Business Hub'&&<section className="hub-page"><article className="panel"><p className="eyebrow">BUSINESS HUB</p><h2>Growth and automation</h2><p className="muted">Recurring invoices, product catalogue, payment follow-up, customer intelligence, automation and revenue pulse are being brought into the unified workspace.</p><div className="hub-grid large"><button onClick={()=>setNotice('Recurring invoices module is queued for the next build batch.')}><ReceiptText/><span>Recurring invoices</span></button><button onClick={()=>setNotice('Products catalogue module is queued for the next build batch.')}><MoreHorizontal/><span>Products & services</span></button><button onClick={()=>setNotice('Payment reminders module is queued for the next build batch.')}><CreditCard/><span>Payment follow-up</span></button><button onClick={()=>nav('Reports')}><BarChart3/><span>Revenue pulse</span></button></div></article></section>}
   </main>
  </div>
  {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">DONIDEX</p><h2>{modal==='profile'?'User Profile':modal==='settings'?'Business Settings':modal==='security'?'Security & Account':modal==='ownerTopUp'?'Owner Top-Up':'Plans & Billing'}</h2></div><button className="icon-btn" onClick={()=>setModal(null)} aria-label="Close dialog"><X size={18}/></button></div>{modal==='profile'&&<div className="form-grid"><label>Username<input value={profile.username} onChange={e=>setProfile({...profile,username:e.target.value})}/></label><label>Email<input value={profile.email} readOnly/></label><small className="muted">Your profile is synchronized with your verified DONIDEX account.</small><button className="primary" onClick={()=>void saveProfile()} disabled={profileBusy}>{profileBusy?'Saving…':'Save profile'}</button></div>}{modal==='settings'&&<div className="form-grid"><label>Business name<input value={business.name} onChange={e=>setBusiness({...business,name:e.target.value})}/></label><label>Phone<input value={business.phone} onChange={e=>setBusiness({...business,phone:e.target.value})}/></label><label>Email<input value={business.email} onChange={e=>setBusiness({...business,email:e.target.value})}/></label><label>Address<input value={business.address} onChange={e=>setBusiness({...business,address:e.target.value})}/></label><label>Tax %<input type="number" value={business.tax} onChange={e=>setBusiness({...business,tax:Number(e.target.value)})}/></label><label>Invoice prefix<input value={business.prefix} onChange={e=>setBusiness({...business,prefix:e.target.value.toUpperCase()})}/></label><button className="primary" onClick={()=>{persist('business',business);setNotice('Business settings saved.');setModal(null)}}>Save settings</button></div>}{modal==='security'&&<div className="security-box"><ShieldCheck size={28}/><h3>Account security</h3><p>{user?.email||'Verified DONIDEX account'}</p><p>Email verification is active. Use the controls below to manage access securely.</p><div className="actions"><button className="secondary" onClick={()=>void resetPassword()} disabled={securityBusy}>{securityBusy?'Working…':'Send password reset'}</button><button className="secondary" onClick={()=>void logout()} disabled={securityBusy}>Sign out</button></div></div>}{modal==='plans'&&<BillingCenter embedded />}{modal==='ownerTopUp'&&<OwnerTopUp onClose={()=>setModal(null)}/>}</div></div>}
  {notice&&<div className="toast" role="status">{notice}</div>}
 </div>;
}
