import { useEffect, useState } from 'react';
import { Check, CreditCard, ExternalLink, X } from 'lucide-react';
import { onAuthStateChanged, type User } from 'firebase/auth';
import { doc, getDoc } from 'firebase/firestore';
import { auth, db } from './lib/firebase';

type Price = { key: string; name: string; interval: 'month'|'year'; amount: number; priceId: string };
type BillingHistoryItem = { id:string; plan:string; status:string; interval?:string|null; amount:number; currency:string; start?:string|null; nextPayment?:string|null };
type BillingStatus = { plan: string; status: string; entitlementActive: boolean; subscriptionId?: string | null; source?: string; history?: BillingHistoryItem[] };

const billingBase = String(import.meta.env.VITE_PAYSTACK_API_BASE || '').replace(/\/+$/, '');
const billingUrl = (route: string, query = '') => billingBase ? `${billingBase}/${route}${query}` : `/api/billing/${route}${query}`;
const formatDate = (value?: string|null) => value ? new Date(value).toLocaleDateString('en-NG',{year:'numeric',month:'short',day:'numeric'}) : '—';

export default function BillingCenter({ embedded = false }: { embedded?: boolean }) {
 const [user, setUser] = useState<User | null>(null); const [open, setOpen] = useState(embedded); const [prices, setPrices] = useState<Price[]>([]); const [billing, setBilling] = useState<BillingStatus>({ plan: 'Free', status: 'none', entitlementActive: false, history: [] }); const [busy, setBusy] = useState(''); const [message, setMessage] = useState('');
 useEffect(() => { if (!auth) return; return onAuthStateChanged(auth, value => setUser(value?.emailVerified ? value : null)); }, []);
 const authHeaders = async () => { const token = await user?.getIdToken(); if (!token) throw new Error('Your authenticated session is required.'); return { Authorization: `Bearer ${token}` }; };
 const load = async () => { setMessage(''); try { const headers = await authHeaders(); const catalogPromise = fetch(billingUrl('catalog')); const statusPromise = fetch(billingUrl('status', `?email=${encodeURIComponent(user?.email || '')}`), { headers }); const [catalog, status] = await Promise.all([catalogPromise, statusPromise]); const data = await catalog.json(); const state = await status.json().catch(() => null); if (!catalog.ok) throw new Error(data.error || 'Could not load billing plans.'); if (!status.ok) throw new Error(state?.error || 'Could not load your billing status.'); setPrices(data.prices || []); let next: BillingStatus = state; if (db && user) { const overrideSnap = await getDoc(doc(db, 'ownerTopUps', user.uid)); if (overrideSnap.exists()) { const override = overrideSnap.data() as any; const active = new Date(override.endsAt || 0).getTime() > Date.now(); if (active) next = { ...next, plan: override.plan || 'Premium', status: `owner recovery · ${override.interval || 'month'}`, entitlementActive: true, source: 'owner-manual-recovery' }; } } setBilling(next); setOpen(true); } catch (e) { setMessage(e instanceof Error ? e.message : 'Could not load billing plans.'); setOpen(true); } };
 useEffect(() => { if (embedded && user) void load(); }, [embedded, user]);
 useEffect(() => { const params = new URLSearchParams(window.location.search); const reference = params.get('reference'); const returned = params.get('billing') === 'paystack-return'; if (!returned || !reference || !user) return; let cancelled = false; const verify = async () => { setOpen(true); setBusy('verify'); setMessage('Verifying your Paystack payment securely…'); try { const headers = await authHeaders(); const r = await fetch(billingUrl('verify', `?reference=${encodeURIComponent(reference)}`), { headers }); const data = await r.json().catch(() => null); if (!r.ok || !data?.verified) throw new Error(data?.error || 'Payment could not be verified yet.'); if (!cancelled) setMessage(`Payment verified successfully${data.plan ? ` for ${data.plan}` : ''}. Refreshing your subscription status…`); await load(); } catch (e) { if (!cancelled) setMessage(e instanceof Error ? e.message : 'Payment verification failed.'); } finally { if (!cancelled) { setBusy(''); const clean = new URL(window.location.href); clean.searchParams.delete('billing'); clean.searchParams.delete('reference'); window.history.replaceState({}, '', `${clean.pathname}${clean.search}${clean.hash}`); } } }; void verify(); return () => { cancelled = true; }; }, [user]);
 const checkout = async (planCode: string) => { if (!planCode) { setMessage('This Paystack plan is not configured yet.'); return; } setBusy(planCode); setMessage(''); try { const headers = { ...(await authHeaders()), 'Content-Type':'application/json' }; const r = await fetch(billingUrl('checkout'), { method:'POST', headers, body:JSON.stringify({ priceId: planCode, customerEmail:user?.email, userId:user?.uid }) }); const data = await r.json(); if (!r.ok || !data.url) throw new Error(data.error || 'Paystack checkout could not be started.'); window.location.href = data.url; } catch (e) { setMessage(e instanceof Error ? e.message : 'Paystack checkout could not be started.'); setBusy(''); } };
 const manage = async () => { if (!billing.subscriptionId) return; setBusy('manage'); setMessage(''); try { const headers = { ...(await authHeaders()), 'Content-Type':'application/json' }; const r = await fetch(billingUrl('portal'), { method:'POST', headers, body:JSON.stringify({ subscriptionCode: billing.subscriptionId }) }); const data = await r.json(); if (!r.ok || !data.url) throw new Error(data.error || 'Subscription management could not be opened.'); window.location.href = data.url; } catch (e) { setMessage(e instanceof Error ? e.message : 'Subscription management could not be opened.'); setBusy(''); } };
 if (!user) return null;
 const body = <section className="billing-modal" onClick={e => e.stopPropagation()}><div className="billing-head"><div><p className="eyebrow">DONIDEX COMMERCIAL</p><h2>Plans & billing</h2><p>Choose a recurring Paystack plan. Annual billing saves two months.</p></div>{!embedded && <button className="icon-btn" onClick={() => setOpen(false)} aria-label="Close billing"><X size={18}/></button>}</div><div className="billing-current"><span>Current plan</span><strong>{billing.plan}</strong><small>{billing.source === 'owner-manual-recovery' ? 'Owner-verified payment recovery' : billing.status === 'none' ? 'No active subscription' : billing.status.replace('_', ' ')}</small>{billing.subscriptionId && <button className="secondary" onClick={() => void manage()} disabled={busy === 'manage'}><ExternalLink size={14}/> {busy === 'manage' ? 'Opening…' : 'Manage subscription'}</button>}</div><div className="billing-grid">{prices.map(p => <article className="billing-card" key={p.key}><span>{p.name}</span><strong>₦{p.amount.toLocaleString('en-NG')}<small>/{p.interval}</small></strong><ul><li><Check size={14}/> Secure Paystack checkout</li><li><Check size={14}/> Recurring billing</li></ul><button className="primary" disabled={busy === p.priceId || !p.priceId} onClick={() => void checkout(p.priceId)}>{busy === p.priceId ? 'Opening checkout…' : !p.priceId ? 'Not configured' : `Choose ${p.interval}`}</button></article>)}</div><div className="billing-history"><div className="panel-head"><div><p className="eyebrow">BILLING HISTORY</p><h3>Subscription activity</h3></div><button className="ghost" onClick={() => void load()} disabled={Boolean(busy)}>Refresh</button></div>{billing.history?.length ? billing.history.map(item => <div className="billing-history-row" key={item.id}><div><strong>{item.plan}</strong><span>{item.interval ? `${item.interval} · ` : ''}{formatDate(item.start)}</span></div><b>{item.amount ? `₦${item.amount.toLocaleString('en-NG')}` : '—'}</b><em>{item.status}</em><span>{item.nextPayment ? `Next: ${formatDate(item.nextPayment)}` : 'No next payment'}</span></div>) : <p className="muted">No subscription history is available yet.</p>}</div>{message && <div className="billing-message" role="status" aria-live="polite">{message}</div>}<small className="billing-note">Free remains ₦0. Premium: ₦5,000/month or ₦50,000/year. Business / Team: ₦15,000/month or ₦150,000/year.</small></section>;
 return <>{!embedded && <button className="billing-launcher" onClick={() => void load()} aria-label="Open plans and billing"><CreditCard size={16}/> Plans & Billing</button>}{open && <div className="billing-backdrop" onClick={() => !embedded && setOpen(false)}>{body}</div>}</>;
}
