import { useEffect, useState } from 'react';
import { Check, CreditCard, ExternalLink, X } from 'lucide-react';
import { onAuthStateChanged, type User } from 'firebase/auth';
import { doc, getDoc } from 'firebase/firestore';
import { auth, db } from './lib/firebase';

type Price = { key: string; name: string; interval: 'month'|'year'; amount: number; priceId: string };
type BillingStatus = { plan: string; status: string; entitlementActive: boolean; subscriptionId?: string | null; source?: string };

const projectId = import.meta.env.VITE_FIREBASE_PROJECT_ID as string | undefined;
const billingBase = projectId ? `https://us-central1-${projectId}.cloudfunctions.net/paystackBilling` : '';
const billingUrl = (route: string, query = '') => billingBase ? `${billingBase}/${route}${query}` : `/api/billing/${route}${query}`;

export default function BillingCenter() {
 const [user, setUser] = useState<User | null>(null); const [open, setOpen] = useState(false); const [prices, setPrices] = useState<Price[]>([]); const [billing, setBilling] = useState<BillingStatus>({ plan: 'Free', status: 'none', entitlementActive: false }); const [busy, setBusy] = useState(''); const [message, setMessage] = useState('');
 useEffect(() => { if (!auth) return; return onAuthStateChanged(auth, value => setUser(value?.emailVerified ? value : null)); }, []);
 const load = async () => { setMessage(''); try { const catalogPromise = fetch(billingUrl('catalog')); const statusPromise = fetch(billingUrl('status', `?email=${encodeURIComponent(user?.email || '')}`)); const [catalog, status] = await Promise.all([catalogPromise, statusPromise]); const data = await catalog.json(); const state = await status.json().catch(() => null); if (!catalog.ok) throw new Error(data.error || 'Could not load billing plans.'); setPrices(data.prices || []); let next: BillingStatus = status.ok && state ? state : { plan: 'Free', status: 'none', entitlementActive: false }; if (db && user) { const overrideSnap = await getDoc(doc(db, 'ownerTopUps', user.uid)); if (overrideSnap.exists()) { const override = overrideSnap.data() as any; const active = new Date(override.endsAt || 0).getTime() > Date.now(); if (active) next = { plan: override.plan || 'Premium', status: `owner recovery · ${override.interval || 'month'}`, entitlementActive: true, source: 'owner-manual-recovery' }; } } setBilling(next); setOpen(true); } catch (e) { setMessage(e instanceof Error ? e.message : 'Could not load billing plans.'); setOpen(true); } };
 const checkout = async (planCode: string) => { if (!planCode) { setMessage('This Paystack plan is not configured yet.'); return; } setBusy(planCode); setMessage(''); try { const r = await fetch(billingUrl('checkout'), { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ priceId: planCode, customerEmail:user?.email, userId:user?.uid, callbackUrl:`${window.location.origin}/?billing=paystack-return` }) }); const data = await r.json(); if (!r.ok || !data.url) throw new Error(data.error || 'Paystack checkout could not be started.'); window.location.href = data.url; } catch (e) { setMessage(e instanceof Error ? e.message : 'Paystack checkout could not be started.'); setBusy(''); } };
 const manage = async () => { if (!billing.subscriptionId) return; setBusy('manage'); setMessage(''); try { const r = await fetch(billingUrl('portal'), { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ subscriptionCode: billing.subscriptionId }) }); const data = await r.json(); if (!r.ok || !data.url) throw new Error(data.error || 'Subscription management could not be opened.'); window.location.href = data.url; } catch (e) { setMessage(e instanceof Error ? e.message : 'Subscription management could not be opened.'); setBusy(''); } };
 if (!user) return null;
 return <><button className="billing-launcher" onClick={() => void load()}><CreditCard size={16}/> Plans & Billing</button>{open && <div className="billing-backdrop" onClick={() => setOpen(false)}><section className="billing-modal" onClick={e => e.stopPropagation()}><div className="billing-head"><div><p className="eyebrow">DONIDEX COMMERCIAL</p><h2>Plans & billing</h2><p>Choose a recurring Paystack plan. Annual billing saves two months.</p></div><button className="icon-btn" onClick={() => setOpen(false)}><X size={18}/></button></div><div className="billing-current"><span>Current plan</span><strong>{billing.plan}</strong><small>{billing.source === 'owner-manual-recovery' ? 'Owner-verified payment recovery' : billing.status === 'none' ? 'No active subscription' : billing.status.replace('_', ' ')}</small>{billing.subscriptionId && <button className="secondary" onClick={() => void manage()} disabled={busy === 'manage'}><ExternalLink size={14}/> {busy === 'manage' ? 'Opening…' : 'Manage subscription'}</button>}</div><div className="billing-grid">{prices.map(p => <article className="billing-card" key={p.key}><span>{p.name}</span><strong>₦{p.amount.toLocaleString('en-NG')}<small>/{p.interval}</small></strong><ul><li><Check size={14}/> Secure Paystack checkout</li><li><Check size={14}/> Recurring billing</li></ul><button className="primary" disabled={busy === p.priceId || !p.priceId} onClick={() => void checkout(p.priceId)}>{busy === p.priceId ? 'Opening checkout…' : !p.priceId ? 'Not configured' : `Choose ${p.interval}`}</button></article>)}</div>{message && <div className="billing-message">{message}</div>}<small className="billing-note">Free remains ₦0. Premium: ₦5,000/month or ₦50,000/year. Business / Team: ₦15,000/month or ₦150,000/year.</small></section></div>}</>;
}
