import { useState } from 'react';
import { Copy, MessageCircle, Pencil, Printer, ReceiptText, X } from 'lucide-react';

type Doc={id:string;number:string;customer:string;total:number;status:'Draft'|'Sent'|'Paid'|'Overdue';due:string;kind?:'Invoice'|'Quotation'};
type Receipt={id:string;number:string;invoiceNumber:string;customer:string;amount:number;date:string;reference:string};

type Props={doc:Doc;docs:Doc[];setDocs:(v:any)=>void;receipts:Receipt[];setReceipts:(v:any)=>void;onClose:()=>void;money:(n:number)=>string};

export default function DocumentWorkflow({doc,docs,setDocs,receipts,setReceipts,onClose,money}:Props){
 const [editing,setEditing]=useState(false); const [draft,setDraft]=useState(doc); const [notice,setNotice]=useState('');
 const save=()=>{setDocs((items:Doc[])=>items.map(x=>x.id===doc.id?draft:x));setNotice('Document saved.');setEditing(false)};
 const duplicate=()=>{const copy={...draft,id:crypto.randomUUID(),number:`${draft.kind==='Quotation'?'QUO':'INV'}-${String(docs.length+1).padStart(4,'0')}`,status:'Draft' as const};setDocs((items:Doc[])=>[copy,...items]);setDraft(copy);setNotice(`${copy.number} duplicated.`)};
 const convert=()=>{const invoice={...draft,id:crypto.randomUUID(),number:`INV-${String(docs.filter(x=>x.kind==='Invoice').length+1).padStart(4,'0')}`,kind:'Invoice' as const,status:'Draft' as const};setDocs((items:Doc[])=>[invoice,...items]);setDraft(invoice);setNotice(`${draft.number} converted to ${invoice.number}.`)};
 const makeReceipt=()=>{if(draft.kind==='Quotation'){setNotice('Convert the quotation to an invoice first.');return}if(draft.status!=='Paid'){setNotice('Receipt creation requires a paid invoice.');return}const r={id:crypto.randomUUID(),number:`RCT-${String(receipts.length+1).padStart(4,'0')}`,invoiceNumber:draft.number,customer:draft.customer,amount:draft.total,date:new Date().toISOString().slice(0,10),reference:`PAY-${Date.now()}`};setReceipts((items:Receipt[])=>[r,...items]);setNotice(`${r.number} created.`)};
 const share=()=>{const text=encodeURIComponent(`DONIDEX ${draft.kind||'Invoice'} ${draft.number}\nCustomer: ${draft.customer}\nTotal: ${money(draft.total)}\nStatus: ${draft.status}`);window.open(`https://wa.me/?text=${text}`,'_blank','noopener,noreferrer')};
 const print=()=>window.print();
 return <div className="modal-backdrop" onClick={onClose}><div className="modal document-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">DOCUMENT PREVIEW</p><h2>{draft.kind||'Invoice'} {draft.number}</h2></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div><div className="document-preview"><div className="doc-brand">DONIDEX</div><h3>{draft.kind||'Invoice'}</h3><p><b>Customer:</b> {draft.customer}</p><p><b>Status:</b> {draft.status}</p><p><b>Due:</b> {draft.due}</p><div className="doc-total">{money(draft.total)}</div></div>{editing?<div className="form-grid"><label>Customer<input value={draft.customer} onChange={e=>setDraft({...draft,customer:e.target.value})}/></label><label>Total<input type="number" value={draft.total} onChange={e=>setDraft({...draft,total:Number(e.target.value)})}/></label><label>Due date<input type="date" value={draft.due} onChange={e=>setDraft({...draft,due:e.target.value})}/></label><button className="primary" onClick={save}>Save changes</button></div>:<div className="actions document-actions"><button className="secondary" onClick={()=>setEditing(true)}><Pencil size={15}/> Edit</button><button className="secondary" onClick={duplicate}><Copy size={15}/> Duplicate</button>{draft.kind==='Quotation'&&<button className="secondary" onClick={convert}>Convert to invoice</button>}{draft.kind!=='Quotation'&&<button className="secondary" onClick={makeReceipt}><ReceiptText size={15}/> Receipt</button>}<button className="secondary" onClick={print}><Printer size={15}/> Print / PDF</button><button className="primary" onClick={share}><MessageCircle size={15}/> WhatsApp</button></div>}{notice&&<p className="notice">{notice}</p>}<div className="receipt-mini"><p className="eyebrow">RECENT RECEIPTS</p>{receipts.slice(0,3).map(r=><span key={r.id}>{r.number} · {r.invoiceNumber} · {money(r.amount)}</span>)}</div></div></div>
}