import React from 'react';
import { createRoot } from 'react-dom/client';
import AuthGate from './AuthGate';
import BillingCenter from './BillingCenter';
import WorkspaceBridge from './WorkspaceBridge';
import BusinessDataBridge from './BusinessDataBridge';
import BusinessSwitcher from './BusinessSwitcher';
import TeamManagement from './TeamManagement';
import './index.css';
import './billing.css';
import './business.css';
import './team.css';
createRoot(document.getElementById('root')!).render(<React.StrictMode><WorkspaceBridge /><BusinessDataBridge /><AuthGate /><BusinessSwitcher /><TeamManagement /><BillingCenter /></React.StrictMode>);
