import React from 'react';
import { createRoot } from 'react-dom/client';
import AuthGate from './AuthGate';
import BillingCenter from './BillingCenter';
import WorkspaceBridge from './WorkspaceBridge';
import BusinessSwitcher from './BusinessSwitcher';
import './index.css';
import './billing.css';
import './business.css';
createRoot(document.getElementById('root')!).render(<React.StrictMode><WorkspaceBridge /><AuthGate /><BusinessSwitcher /><BillingCenter /></React.StrictMode>);
