import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, CreditCard, FileText, X } from 'lucide-react';

type Doc = { id: string; number: string; customer: string; total: number; status: string; due?: string };
type Receipt = { id: string; number: string; invoice: string; customer: string; amount: number; date: string; reference: string };
const money = (n: number) => `₦${n.toLocaleString('en-NG')}`;
const read = <T,>(key: string, fallback: T): T => { try { const raw = localStorage.getItem(`donidex:${key}`); return raw ? JSON.parse(raw) as T : fallback; } catch { return fallback; } };
const write = <T,>(key: string, value: T) => localStorage.setItem(`donidex:${key}`, JSON.stringify(value));

export default function PaymentCenter() {
 const [open, setOpen] = useState(false); const [docs, setDocs] = useState<Doc[]>(() => read('docs', [])); const [receipts, setReceipts] = useState<Receipt[]>(() => read('receipts', [])); const [selected, setSelected] = useState<Doc | null>(null); const [reference, setReference] = useState(''); const [amount, setAmount] = useState(''); const [notice, setNotice] = useState('');
 useEffect(() => write('receipts', receipts), [receipts]);
 const unpaid = useMemo(() => docs.filter(d => d.status !== 'Paid'), [docs]);
 const paidReceipts = useMemo(() => receipts.slice(0, 8), [receipts]);
 const recordPayment = () => { if (!selected) return; const value = Number(amount || selected.total); if (!Number.isFinite(value) || value <= 0 || value > selected.total) { setNotice('Enter a valid payment amount.'); return; } const ref = reference.trim() || `PAY-${Date.now().toString().slice(-8)}`; const receipt: Receipt = { id: crypto.randomUUID(), number: `RCT-${String(receipts.length + 1).padStart(4, '0')}`, invoice: selected.number, customer: selected.customer, amount: value, date: new Date().toISOString().slice(0, 10), reference: ref }; const nextDocs = docs.map(d => d.id === selected.id ? { ...d, status: value >= d.total ? 'Paid' : 'Sent' } : d); setDocs(nextDocs); write('docs', nextDocs); setReceipts(r => [receipt, ...r]); setSelected(null); setReference(''); setAmount(''); setNotice(`${receipt.number} recorded for ${selected.customer}.`); };
 const openReceipt = (r: Receipt) => { const html = `<html><head><title>${r.number}</title><style>body{font-family:Arial;padding:40px;color:#111}h1{margin-bottom:4px}.gold{color:#a67c00}.box{border:1px solid #ddd;padding:20px;border-radius:12px}p{margin:8px 0}</style></head><body><h1>DONIDEX</h1><p class='gold'>Payment Receipt</p><div class='box'><p><b>Receipt:</b> ${r.number}</p><p><b>Invoice:</b> ${r.invoice}</p><p><b>Customer:</b> ${r.customer}</p><p><b>Amount:</b> ${money(r.amount)}</p><p><b>Date:</b> ${r.date}</p><p><b>Reference:</b> ${r.reference}</p></div><script>window.print()</script></body></html>`; const w = window.open('', '_blank'); if (w) { w.document.write(html); w.document.close(); } };
 return <><button className='payment-launcher' onClick={() => setOpen(true)}><CreditCard size={16}/> Payments</button>{open && <div className='payment-backdrop' onClick={() => setOpen(false)}><section className='payment-modal' onClick={e => e.stopPropagation()}><header><div><p className='eyebrow'>DONIDEX PAYMENTS</p><h2>Payments & receipts</h2><p>Record customer payments and generate professional receipts.</p></div><button className='icon-btn' onClick={() => setOpen(false)}><X size={18}/></button></header>{notice && <div className='payment-notice'>{notice}</div>}<div className='payment-grid'><div className='payment-panel'><div className='payment-panel-head'><h3>Awaiting payment</h3><span>{unpaid.length}</span></div>{unpaid.length ? unpaid.map(d => <div className='payment-row' key={d.id}><div><strong>{d.number}</strong><small>{d.customer}</small></div><b>{money(d.total)}</b><button className='primary' onClick={() => { setSelected(d); setAmount(String(d.total)); }}>Record</button></div>) : <p className='muted'>No unpaid invoices.</p>}</div><div className='payment-panel'><div className='payment-panel-head'><h3>Recent receipts</h3><span>{receipts.length}</span></div>{paidReceipts.length ? paidReceipts.map(r => <button className='receipt-row' key={r.id} onClick={() => openReceipt(r)}><span><strong>{r.number}</strong><small>{r.customer} · {r.invoice}</small></span><b>{money(r.amount)}</b><FileText size={15}/></button>) : <p className='muted'>Receipts will appear here after payments are recorded.</p>}</div></div>{selected && <div className='payment-form'><div><p className='eyebrow'>RECORD PAYMENT</p><h3>{selected.number} · {selected.customer}</h3></div><label>Amount<input inputMode='decimal' value={amount} onChange={e => setAmount(e.target.value)}/></label><label>Payment reference<input value={reference} onChange={e => setReference(e.target.value)} placeholder='e.g. bank transfer reference'/></label><div className='payment-form-actions'><button className='secondary' onClick={() => setSelected(null)}>Cancel</button><button className='primary' onClick={recordPayment}><CheckCircle2 size={15}/> Confirm payment</button></div></div>}</section></div>}</>;
}
