import { useEffect, useState } from 'react';
import { collection, deleteDoc, doc, getDoc, getDocs, setDoc } from 'firebase/firestore';
import { onAuthStateChanged } from 'firebase/auth';
import { UserPlus, Users, X, ShieldCheck, Trash2, CreditCard } from 'lucide-react';
import { auth, db, firebaseConfigured } from './lib/firebase';
import { loadWorkspace } from './lib/workspace';
import './team.css';

type Member = { id: string; email: string; role: 'admin' | 'staff'; status: 'invited' | 'active'; createdAt: number };

export default function TeamManagement() {
 const [user,setUser]=useState<any>(null); const [open,setOpen]=useState(false); const [members,setMembers]=useState<Member[]>([]); const [email,setEmail]=useState(''); const [role,setRole]=useState<Member['role']>('staff'); const [message,setMessage]=useState(''); const [plan,setPlan]=useState('Free'); const [billingReady,setBillingReady]=useState(false);
 const load=async(uid:string)=>{if(!db)return;const workspace=await loadWorkspace(uid);const businessId=workspace?.activeBusinessId||workspace?.businesses?.[0]?.id;if(!businessId)return;const snap=await getDocs(collection(db,'users',uid,'businesses',businessId,'team'));setMembers(snap.docs.map(d=>d.data() as Member));};
 const loadBilling=async(u:any)=>{try{const r=await fetch(`/api/billing/status?email=${encodeURIComponent(u.email||'')}`);const data=await r.json();let nextPlan=data?.plan||'Free';let active=Boolean(data?.entitlementActive);if(db){const override=await getDoc(doc(db,'ownerTopUps',u.uid));if(override.exists()){const value=override.data() as any;if(value.status==='active'&&new Date(value.endsAt||0).getTime()>Date.now()){nextPlan=value.plan||'Premium';active=true;}}}setPlan(nextPlan);setBillingReady(active);}catch{setPlan('Free');setBillingReady(false);}};
 useEffect(()=>{if(!auth)return;return onAuthStateChanged(auth,u=>{setUser(u?.emailVerified?u:null);if(u?.emailVerified){void load(u.uid);void loadBilling(u);}});},[]);
 const invite=async()=>{if(!user||!db||!email.trim())return;if(plan!=='Business / Team'||!billingReady){setMessage('Team & Staff requires an active Business / Team subscription.');return;}const workspace=await loadWorkspace(user.uid);const businessId=workspace?.activeBusinessId||workspace?.businesses?.[0]?.id;if(!businessId)return;const member:Member={id:crypto.randomUUID(),email:email.trim().toLowerCase(),role,status:'invited',createdAt:Date.now()};await setDoc(doc(db,'users',user.uid,'businesses',businessId,'team',member.id),member);setMembers(v=>[member,...v]);setEmail('');setMessage('Team member invitation staged.');};
 const remove=async(id:string)=>{if(!user||!db||plan!=='Business / Team'||!billingReady){setMessage('Team management requires an active Business / Team subscription.');return;}const workspace=await loadWorkspace(user.uid);const businessId=workspace?.activeBusinessId||workspace?.businesses?.[0]?.id;if(!businessId)return;await deleteDoc(doc(db,'users',user.uid,'businesses',businessId,'team',id));setMembers(v=>v.filter(m=>m.id!==id));};
 if(!user||!firebaseConfigured)return null;
 return <><button className="team-launcher" onClick={()=>{setMessage('');setOpen(true)}}><Users size={16}/> Team</button>{open&&<div className="team-backdrop" onClick={()=>setOpen(false)}><section className="team-modal" onClick={e=>e.stopPropagation()}><header><div><p className="eyebrow">BUSINESS / TEAM</p><h2>Team & staff</h2><p>Business / Team subscribers can manage role-based access for their business.</p></div><button className="icon-btn" onClick={()=>setOpen(false)}><X size={18}/></button></header>{plan!=='Business / Team'||!billingReady?<div className="team-upgrade"><CreditCard size={27}/><h3>Business / Team access required</h3><p>Your current plan is <strong>{plan}</strong>. Team accounts are available on the locked Business / Team plan.</p><small>₦15,000/month or ₦150,000/year.</small></div>:<><div className="team-form"><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Staff email address" type="email"/><select value={role} onChange={e=>setRole(e.target.value as Member['role'])}><option value="staff">Staff</option><option value="admin">Admin</option></select><button className="primary" onClick={()=>void invite()}><UserPlus size={15}/> Add member</button></div>{message&&<div className="team-message">{message}</div>}<div className="team-list">{members.length?members.map(m=><div className="team-row" key={m.id}><div><strong>{m.email}</strong><span>{m.status} · {m.role}</span></div><ShieldCheck size={17}/><button className="icon-btn" onClick={()=>void remove(m.id)} aria-label={`Remove ${m.email}`}><Trash2 size={15}/></button></div>):<div className="team-empty">No team members yet.</div>}</div><small className="team-note">Invitation delivery and server-side role enforcement remain protected backend work; staged members are not granted workspace access automatically.</small></>}</section></div>}</>;
}
