import { useEffect, useState } from 'react';
import { collection, deleteDoc, doc, getDoc, getDocs, query, setDoc, updateDoc, where } from 'firebase/firestore';
import { onAuthStateChanged } from 'firebase/auth';
import { UserPlus, Users, X, ShieldCheck, Trash2, CreditCard } from 'lucide-react';
import { auth, db, firebaseConfigured } from './lib/firebase';
import { loadWorkspace } from './lib/workspace';
import './team.css';

type Member={id:string;email:string;role:'admin'|'staff';status:'invited'|'active';createdAt:number};
type Invite={id:string;email:string;ownerUid:string;businessId:string;role:'admin'|'staff';status:'pending'|'accepted';createdAt:number;acceptedUid?:string};

export default function TeamManagement(){const [user,setUser]=useState<any>(null);const [open,setOpen]=useState(false);const [members,setMembers]=useState<Member[]>([]);const [pendingInvites,setPendingInvites]=useState<Invite[]>([]);const [email,setEmail]=useState('');const [role,setRole]=useState<Member['role']>('staff');const [message,setMessage]=useState('');const [plan,setPlan]=useState('Free');const [billingReady,setBillingReady]=useState(false);
 const loadOwner=async(uid:string)=>{if(!db)return;const workspace=await loadWorkspace(uid);const businessId=workspace?.activeBusinessId||workspace?.businesses?.[0]?.id;if(!businessId)return;const snap=await getDocs(query(collection(db,'teamInvites'),where('ownerUid','==',uid),where('businessId','==',businessId)));const invites=snap.docs.map(d=>({id:d.id,...d.data()} as Invite));setPendingInvites(invites.filter(i=>i.status==='pending'));setMembers(invites.filter(i=>i.status==='accepted').map(i=>({id:i.id,email:i.email,role:i.role,status:'active',createdAt:i.createdAt})))};
 const loadBilling=async(u:any)=>{try{const r=await fetch(`/api/billing/status?email=${encodeURIComponent(u.email||'')}`);const data=await r.json();let nextPlan=data?.plan||'Free';let active=Boolean(data?.entitlementActive);if(db){const override=await getDoc(doc(db,'ownerTopUps',u.uid));if(override.exists()){const value=override.data() as any;if(value.status==='active'&&new Date(value.endsAt||0).getTime()>Date.now()){nextPlan=value.plan||'Premium';active=true;}}}setPlan(nextPlan);setBillingReady(active);}catch{setPlan('Free');setBillingReady(false)}};
 const acceptInvites=async(u:any)=>{if(!db||!u?.email)return;const snap=await getDocs(query(collection(db,'teamInvites'),where('email','==',u.email.toLowerCase()),where('status','==','pending')));for(const item of snap.docs){const invite=item.data() as Invite;await setDoc(doc(db,'teamMemberships',u.uid),{uid:u.uid,ownerUid:invite.ownerUid,businessId:invite.businessId,email:u.email.toLowerCase(),role:invite.role,status:'active',createdAt:invite.createdAt,acceptedAt:Date.now(),inviteId:item.id});await updateDoc(item.ref,{status:'accepted',acceptedUid:u.uid,acceptedAt:Date.now()});}if(snap.size)setMessage(`${snap.size} team invitation${snap.size===1?'':'s'} accepted. Refreshing workspace…`);};
 useEffect(()=>{if(!auth)return;return onAuthStateChanged(auth,async u=>{setUser(u?.emailVerified?u:null);if(!u?.emailVerified)return;await acceptInvites(u);await loadBilling(u);await loadOwner(u.uid);});},[]);
 const invite=async()=>{if(!user||!db||!email.trim())return;if(plan!=='Business / Team'||!billingReady){setMessage('Team & Staff requires an active Business / Team subscription.');return;}const workspace=await loadWorkspace(user.uid);const businessId=workspace?.activeBusinessId||workspace?.businesses?.[0]?.id;if(!businessId)return;const id=crypto.randomUUID();const inviteData:Invite={id,email:email.trim().toLowerCase(),ownerUid:user.uid,businessId,role,status:'pending',createdAt:Date.now()};await setDoc(doc(db,'teamInvites',id),inviteData);setPendingInvites(v=>[inviteData,...v]);setEmail('');setMessage('Team invitation staged. The staff member can accept it after signing in with the invited email.');};
 const remove=async(id:string)=>{if(!user||!db)return;await deleteDoc(doc(db,'teamInvites',id));setPendingInvites(v=>v.filter(i=>i.id!==id));setMembers(v=>v.filter(m=>m.id!==id));setMessage('Team invitation removed.');};
 if(!user||!firebaseConfigured)return null;
 return <><button className="team-launcher" onClick={()=>{setMessage('');setOpen(true)}}><Users size={16}/> Team</button>{open&&<div className="team-backdrop" onClick={()=>setOpen(false)}><section className="team-modal" onClick={e=>e.stopPropagation()}><header><div><p className="eyebrow">BUSINESS / TEAM</p><h2>Team & staff</h2><p>Business / Team subscribers can invite staff and administrators into the business workspace.</p></div><button className="icon-btn" onClick={()=>setOpen(false)}><X size={18}/></button></header>{plan!=='Business / Team'||!billingReady?<div className="team-upgrade"><CreditCard size={27}/><h3>Business / Team access required</h3><p>Your current plan is <strong>{plan}</strong>.</p><small>₦15,000/month or ₦150,000/year.</small></div>:<><div className="team-form"><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Staff email address" type="email"/><select value={role} onChange={e=>setRole(e.target.value as Member['role'])}><option value="staff">Staff</option><option value="admin">Admin</option></select><button className="primary" onClick={()=>void invite()}><UserPlus size={15}/> Invite</button></div>{message&&<div className="team-message">{message}</div>}<div className="team-list">{members.map(m=><div className="team-row" key={m.id}><div><strong>{m.email}</strong><span>active · {m.role}</span></div><ShieldCheck size={17}/><button className="icon-btn" onClick={()=>void remove(m.id)} aria-label={`Remove ${m.email}`}><Trash2 size={15}/></button></div>)}{pendingInvites.map(i=><div className="team-row" key={i.id}><div><strong>{i.email}</strong><span>invited · {i.role}</span></div><button className="icon-btn" onClick={()=>void remove(i.id)} aria-label={`Cancel invitation for ${i.email}`}><Trash2 size={15}/></button></div>)}{!members.length&&!pendingInvites.length&&<div className="team-empty">No team members yet.</div>}</div><small className="team-note">Invitation acceptance creates a protected Firebase membership. Staff access is read-only; administrators can save shared workspace changes.</small></>}</section></div>}</>;
}
